name: Build Digikala Logger APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.0'
          cache: true

      - name: Generate Android Skeleton
        run: flutter create . --platforms=android --org com.digilogger.app --project-name=digi_logger

      - name: Inject Internet Permission and Config
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          sed -i 's/android:label="digi_logger"/android:label="Digi Logger"/g' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: digikala-logger-apk
          path: build/app/outputs/flutter-apk/app-release.apk
